language: node_js
dist: trusty
node_js: "7"
install:
    - npm install -g npm
    - npm install -g @smallstack/cli
    - smallstack setup --mode=url --url=https://s3.eu-central-1.amazonaws.com/smallstack-releases/smallstack-0.9.0-RC8.zip
    - npm install
script:
    - smallstack help
notifications:
  slack: $SLACK_TOKEN
  on_success: change
deploy:
  provider: npm
  email: "max@smallstack.io"
  api_key: $NPM_API_KEY
  on:
    tags: true
